[package]
name = "ygocdb_reader"
version = "0.2.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.25.3"
clap = "2.33.3"

[build-dependencies]
embed-resource = "1.6.3"
